# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CreateStdDistancePointers <- function(types, considerNaNs) {
    .Call(`_kohonenDTW_CreateStdDistancePointers`, types, considerNaNs)
}

CreateStdDistancePointer <- function(type, considerNaNs) {
    .Call(`_kohonenDTW_CreateStdDistancePointer`, type, considerNaNs)
}

ObjectDistances <- function(data, numVars, numNAs, distanceFunctions, weights) {
    .Call(`_kohonenDTW_ObjectDistances`, data, numVars, numNAs, distanceFunctions, weights)
}

RcppSupersom <- function(data, codes, numVars, weights, distanceFunctions, numNAs, neighbourhoodDistances, neighbourhoodFct, alphas, radii, numEpochs) {
    .Call(`_kohonenDTW_RcppSupersom`, data, codes, numVars, weights, distanceFunctions, numNAs, neighbourhoodDistances, neighbourhoodFct, alphas, radii, numEpochs)
}

RcppBatchSupersom <- function(data, codes, numVars, weights, distanceFunctions, numNAs, neighbourhoodDistances, neighbourhoodFct, radii, numEpochs) {
    .Call(`_kohonenDTW_RcppBatchSupersom`, data, codes, numVars, weights, distanceFunctions, numNAs, neighbourhoodDistances, neighbourhoodFct, radii, numEpochs)
}

RcppParallelBatchSupersom <- function(data, codes, numVars, weights, distanceFunctions, numNAs, neighbourhoodDistances, neighbourhoodFct, radii, numEpochs, numCores) {
    .Call(`_kohonenDTW_RcppParallelBatchSupersom`, data, codes, numVars, weights, distanceFunctions, numNAs, neighbourhoodDistances, neighbourhoodFct, radii, numEpochs, numCores)
}

RcppMap <- function(data, numVars, numNAs, codes, weights, distanceFunctions) {
    .Call(`_kohonenDTW_RcppMap`, data, numVars, numNAs, codes, weights, distanceFunctions)
}

